### ISSUE TITLE
Error while compiling injector

### ISSUE THREAD

**Issue by zoythum** [NVlabs/nvbitfi#14]
Working on a Jetson TX2 with the following nvcc version
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_28_22:34:44_PST_2021
Cuda compilation tools, release 10.2, V10.2.300
Build cuda_10.2_r440.TC440_70.29663091_0`

I tried executing `test.sh` on the latest commit `2f558ff89d5ff83025d19a85ae4405ad34bf1974` but it failed while compiling `injector.cu` with the following message

`injector.cu(301): error: identifier "nvbit_add_call_arg_pred_val" is undefined
1 error detected in the compilation of "/tmp/tmpxft_00000271_00000000-6_injector.cpp1.ii".
Makefile:30: recipe for target 'injector.o' failed
make: *** [injector.o] Error 1`

I tried reverting commits and I found the same error on `111519cc4be4f0e0365e141681fa410bd24c9528` while it compiles correctly at `4726929de5ae023bf9853327bac5a8254e027e52`. Is it a problem of my configuration or on the code itself? 

Thanks for the help

**Comment by fernandoFernandeSantos** [comment]
Hi @zoythum 
I have the same problem, have you found any solution for this issue?
I have tried to replace it with nvbit_add_call_arg_guard_pred_val, it builds correctly, but I don`t know if it is correct or not.

Thanks

**Comment by sivahari** [comment]
In NVBit-1.5, `*_pred` functions/variables were changed to `*_guard_pred`. We pushed changes to injector.cu and profiler.cu to address this issue. Thanks for reporting it.
