### ISSUE TITLE
Some small version fixes for nvbitfi 

### ISSUE THREAD

**Issue by xinyi-li7** [NVlabs/nvbitfi#15]
Hi, 
  When I was trying to run the first experiment `test.sh` in `README.md,` I found there're several errors caused by the version: 
1. In the 1.5 version of NVBit, it changed *_pred functions/variables to *_guard_pred, see its [log](https://github.com/NVlabs/NVBit/releases). So I think you may want to change the function `nvbit_add_call_arg_pred_val(i)` to `nvbit_add_call_arg_guard_pred_val(i)` in both `injector.cu` and `profiler.cu`. 
2. I noticed that you may use python 2.0, so I received errors like `TypeError: can only concatenate list (not "map") to list`. I wondered if you could surround `map()` with `list()` when you are doing `join` function in `parse_results.py`. 

Sorry for these small suggestions, I think it's OK if you just keep the current version since the developers may find themselves. Thanks!

**Comment by sivahari** [comment]
Thanks. The latest version incorporates your suggestions.
