### ISSUE TITLE
Error running test.sh

### ISSUE THREAD

**Issue by hugocth** [NVlabs/nvbitfi#2]
Hello, I'm an engineering student trying to run this benchmark on a Jetson Nano. I run Ubuntu 18.04 and Cuda 10.2, however when I run test.sh (after succesfully havig completed the previous instructions in the README), I get these errors. Do you have any ideas how to fix it ? I tried to Google it and I didn't find anything concerning the -lnvbit module ...
Thanks a lot by advance !

> Step 0 (3): Build the nvbitfi injector and profiler tools
> nvcc -ccbin=`which gcc` -D_FORCE_INLINES -arch=sm_35 -O3 inject_funcs.o injector.o -L../../../core -lnvbit -L/usr/local/cuda/lib64 -lcuda -lcudart_static -shared -o injector.so
> nvlink warning : Skipping incompatible '../../../core/libnvbit.a' when searching for -lnvbit
> /usr/bin/ld: skipping incompatible ../../../core/libnvbit.a when searching for -lnvbit
> /usr/bin/ld: cannot find -lnvbit
> collect2: error: ld returned 1 exit status
> Makefile:27: recipe for target 'injector.so' failed
> make: *** [injector.so] Error 1
>

**Comment by sivahari** [comment]
You may be using the x86 version. Please try using [aarch64 ](https://github.com/NVlabs/NVBit/releases/download/1.5.3/nvbit-Linux-aarch64-1.5.3.tar.bz2) version. ARM support was added starting NVBit version 1.3.1.

I'll update the NVBitFI instructions to reflect this change.

**Comment by hugocth** [comment]
Thank you for your quick answer ! I'll try late and I'll update you.

**Comment by amir-ahsaei** [comment]
Hi @sivahari,
I tried both @hugocth and your ararch64 version but, got the same error as follows:

Step 0 (3): Build the nvbitfi injector and profiler tools
nvcc -ccbin=`which gcc` -D_FORCE_INLINES -I../../../core -I../common -maxrregcount=16 -Xptxas -astoolspatch --keep-device-functions -arch=sm_35 -DDUMMY=0 -Xcompiler -Wall -Xcompiler -fPIC -c inject_funcs.cu -o inject_funcs.o
nvcc -ccbin=`which gcc` -D_FORCE_INLINES -dc -c -std=c++11 -I../../../core -I../common -Xptxas -cloning=no -Xcompiler -Wall -arch=sm_35 -O3 -Xcompiler -fPIC injector.cu -o injector.o
nvcc -ccbin=`which gcc` -D_FORCE_INLINES -arch=sm_35 -O3 inject_funcs.o injector.o -L../../../core -lnvbit -L/usr/local/cuda/lib64 -lcuda -lcudart_static -shared -o injector.so
nvlink warning : Skipping incompatible '../../../core/libnvbit.a' when searching for -lnvbit
/usr/bin/ld: skipping incompatible ../../../core/libnvbit.a when searching for -lnvbit
/usr/bin/ld: cannot find -lnvbit
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Makefile:27: recipe for target 'injector.so' failed
make: *** [injector.so] Error 1


Is there anything that I am missing? This is my system configuration:
NVIDIA-SMI 450.119.04   
Driver Version: 450.119.04   
CUDA Version: 11.0
gcc version: 7.5.0
nvcc version: release 10.2, V10.2.89
GPU model: Tesla P100

Thank you.
