### ISSUE TITLE
question on RTX Titan, thanks

### ISSUE THREAD

**Issue by wzdutd** [NVlabs/nvbitfi#4]
Hello, 

As you said, the tool should support turning. However, when I executed it in Titan RTX, it shows error "does not support Titan RTX". I wondered whether you can provide us with any suggestions. Thanks

**Comment by sivahari** [comment]
Hi, Please try using the latest NVbit (https://github.com/NVlabs/NVBit/releases/tag/1.5.3), in case you are using version 1.3. Some bugs were fixed in the recent versions related to Turing support (https://github.com/NVlabs/NVBit/releases).
